projectFiles/models.py
# importing all the packages
from flask_sqlalchemy import SQLAlchemy
from projectFiles import db
from datetime import datetime
timeNow = datetime.now()

#database tables 
class Task(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    datePost = db.Column(db.DateTime, default=timeNow)
    content = db.Column(db.Text, nullable=False)

#completed database tables
class Complated(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    datePost = db.Column(db.DateTime)
    content = db.Column(db.Text, nullable=False)

projectFiles/__init__.py
# import all the packigs
from flask import Flask, Blueprint
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from projectFiles.config import Config


# Database launch and the migration
db = SQLAlchemy()
migrate = Migrate()

# the main app function
def create_app(config_class=Config):
    # the Flask class instaince 
    app = Flask(__name__)
    # import the configration from config file
    app.config.from_object(Config)
    db.init_app(app)
    migrate.init_app(app, db)
    # create the database
    with app.app_context():
        from projectFiles import models
        db.create_all()
    # register the main blueprint
    from projectFiles.main.routes import home_page
    app.register_blueprint(home_page)
    return app

projectFiles/main/routes.py
#importing all the packages
from flask import Blueprint, redirect, render_template, url_for, request, flash, redirect
from projectFiles.models import Task, Complated
from projectFiles import db
from projectFiles.main.function import check, delete

# the main blueprint
home_page = Blueprint('home', __name__,
    template_folder='templates',
    static_folder='static')

# I am not going to explain this nonsense. You should be familiar with the flask framework
@home_page.route("/", methods=["POST", "GET"])
@home_page.route("/todolist", methods=["POST", "GET"])
def home():
    if request.method == "POST":
        delete()
        newTask = request.form.get("task")
        if newTask == "":
            combltedTask = Complated.query.order_by(Complated.datePost.desc()).all()
            allTasks = Task.query.order_by(Task.datePost.desc()).all()
            flash("please inter a task", "danger")
            return render_template("index.html", title="TODOlist", allTasks=allTasks, combltedTask=combltedTask)
        else:
            functionResult = check(newTask)
            if functionResult:
                new = Task(content=newTask)
                db.session.add(new)
                db.session.commit()
                combltedTask = Complated.query.order_by(Complated.datePost.desc()).all()
                allTasks = Task.query.order_by(Task.datePost.desc()).all()
                return render_template("index.html", title="TODOlist", allTasks=allTasks, combltedTask=combltedTask)
            else:
                flash("seem task already threre", "warning")
                combltedTask = Complated.query.order_by(Complated.datePost.desc()).all()
                allTasks = Task.query.order_by(Task.datePost.desc()).all()
                return render_template("index.html", title="TODOlist", allTasks=allTasks, combltedTask=combltedTask)
    combltedTask = Complated.query.order_by(Complated.datePost.desc()).all()
    delete()
    allTasks = Task.query.order_by(Task.datePost.desc()).all()
    return render_template("index.html", title="TODOlist", allTasks=allTasks, combltedTask=combltedTask)


@home_page.route("/delete/<int:id>", methods=["GET"])
def deleteFunction(id):
    task = Task.query.filter_by(id=id).first()
    if task:
        newComplted = Complated(datePost=task.datePost, content=task.content)
        deleteTask = Task.query.filter_by(id=id).delete()
        db.session.add(newComplted)
        db.session.commit()

    allTasks = Task.query.order_by(Task.datePost.desc()).all()
    combltedTask = Complated.query.order_by(Complated.datePost.desc()).all()
    return render_template("index.html", title="TODOlist", allTasks=allTasks, combltedTask=combltedTask)


    

projectFiles/templates/index.html
{%extends "layout.html"%}
{%block title%}{{title}}{%endblock%}
{%block main%}
<main>
  <div>
    <br>
    <br>
    <br>
    <br>
    <br>
    <div class="container">
      {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          {% for category, message in messages %}
            <div class="alert alert-{{ category }} alert-dismissible fade show">
              {{ message }}
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
          {% endfor %}
        {% endif %}
      {% endwith %}
      <div class="row">
          <div class="col-sm-12" id="co1">
              <form action="{{url_for('home.home')}}" method="POST" class="text-center">
                  <div class="form-group text-center">
                    </div>
                    <input type="text" class="form-control text-center" id="text" id="input" name="task" width="100px" placeholder="new task">
                    <button type="submit" class="btn btn-primary text-center btn-md col-sm-12" id="b1">Add</button>
                  </div>
              </form>
          </div>
      </div>    
    </div>
    <div class="container">
      <div class="row">
        {%if allTasks%}
          {%for task in allTasks%}
            <div class="col-sm-4" id="co2">
              <div class="card text-center">
                <div class="card-body">
                    <h5 class="card-title">Task</h5>
                    <p class="card-text">{{task.content}}</p>
                    <div class="co3">
                    <a href="{{url_for('home.deleteFunction', id=task.id)}}" class="btn btn-success">Complete</a>
                    </div>
                </div>
              </div>
            </div>
          {%endfor%}
        {%else%}
          <div class="col-sm-12" id="co2">
            <div class="card text-center">
              <div class="card-body">
                  <p class="card-text">You have a lot to do and you can't remember it all. Add a task</p>
              </div>
            </div>
          </div>
        {%endif%}
      </div>   
      <h3 id="hedline" class="text-center">Completed</h3>
      <hr>
      {%if combltedTask%}
        {%for task in combltedTask%}
          <div class="col-sm-12" id="card">
              <div class="card text-center">
                  <div class="card-body">
                    <p class="card-text">{{task.content}}</p>
                  </div>
              </div>
          </div>
        {%endfor%}
      {%else%}
        <div class="col-sm-12" id="co2">
          <div class="card text-center">
            <div class="card-body">
                <p class="card-text">The completed tasks will show here</p>
            </div>
          </div>
        </div>
      {%endif%}
    </div>
  </div>
</main>
{%endblock%}

projectFiles/templates/layout.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link rel="stylesheet" href="{{url_for('static', filename='index.css')}}">
    <title>{%block title%}{%endblock%}</title>
</head>

<body>
    <div class="all">
        <!-- As a heading -->
        <nav class="navbar fixed-top">
            <span class="navbar-brand mb-0 h1">To-Do list</span>
        </nav>
    </div>
    {%block main%}{%endblock%}
    <div class="all">
        <!-- Footer -->
        <div class="row">
            <br>
            <br>
            <br>
            <br>
            <br>
            <div class="col-md-12">
            <div>
                <footer id="site-footer " class="py-4 bg-dark text-white-50 sticky-bottom footer">
                <div class="text-center">
                <strong>Copyright &copy; <a href="https://www.facebook.com/ibrahim.hanafi.925">Ibrahim Hanafi</a></strong>
                </div>
                </footer>
            </div>
            </div>
        </div>
    <!-- Footer -->
    </div>
  
    
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="{{url_for('static', filename='index.js')}}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
</body>
</html>